name: Build ARMv7

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  linux-armv7:
    name: Build ARMv7
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run VM
        uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: armv7
          distro: alpine_latest
          githubToken: ${{ github.token }}
          run: |
            uname -a
            apk update
            apk add --no-cache cmake make g++ libvulkan-dev wayland-dev libxrandr-dev libxcb-randr0-dev dconf-dev dbus-dev imagemagick-dev xfconf-dev sqlite-dev rpm-dev egl-dev osmesa-dev opencl-dev pulseaudio-dev libdrm-dev elfutils-dev
            cmake -DSET_TWEAK=Off -DBUILD_TESTS=On -DCMAKE_INSTALL_PREFIX=/usr .
            cmake --build . --target package --verbose -j4
            ./fastfetch --list-features
            time ./fastfetch -c presets/ci.jsonc --stat false
            time ./fastfetch -c presets/ci.jsonc --format json
            time ./flashfetch
            ldd fastfetch
            ctest

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fastfetch-linux-armv7
          path: ./fastfetch-*.*
